// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_days_12data from "./routes/api/days/12data.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $days_12 from "./routes/days/12.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Day12Map from "./islands/Day12Map.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/days/12data.ts": $api_days_12data,
    "./routes/api/joke.ts": $api_joke,
    "./routes/days/12.tsx": $days_12,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Day12Map.tsx": $Day12Map,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
